config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations'
  }
  # Defines the root path route ("/")
  root "users#index"

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create] do
      resources :comments, only: %i[index show new create edit update destroy]
      resources :likes, only: %i[index show create destroy]
    end
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
  has_many :posts, class_name: 'Post', foreign_key: 'author_id'
  has_many :comments, class_name: 'Comment', foreign_key: 'user_id'
  has_many :likes, class_name: 'Like', foreign_key: 'user_id'

  def recent_posts
    posts.limit(3).order(created_at: :asc)
  end

  def liked?(post)
    likes.exists?(post:)
  end

  validates :name, presence: true
  validates :posts_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/controllers/users/confirmations_controller.rb
class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  def create
    self.resource = resource_class.find_by_email(resource_params[:email])
    confirmation_url = confirmation_url(@user, confirmation_token: @user.confirmation_token)
    UserMailer.confirmation_email(resource, confirmation_url).deliver_now
    super
  end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
class Users::RegistrationsController < Devise::RegistrationsController
  prepend_before_action :require_no_authentication, only: %i[new create]
  prepend_before_action :authenticate_scope!, only: %i[edit update destroy]

  private

  def sign_up_params
    params.require(:user).permit(:name, :email, :bio, :photo_url, :password, :password_confirmation)
  end

  def account_update_params
    params.require(:user).permit(:name, :email, :bio, :photo_url, :password, :password_confirmation, :current_password)
  end
end

app/controllers/users/sessions_controller.rb
class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]

  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  def destroy
    sign_out(current_user)
    flash[:notice] = 'You have successfully logged out'
    redirect_to root_path
  end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
    @recent_posts = @user.recent_posts
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/index.html.erb
<h1>Users index page</h1>
<% @users.each do |user| %>
<div style="display: flex; gap: 1rem; margin: 1rem;">
  <img src="<%= user.photo %>"/>
  <a href="<%= user_path(user)%>" style="border: 1px solid #000; display: flex; justify-content: space-between; padding: 1rem; width: 100%;">
    <p><%= user.name %></p>
    <p>Number of Posts: <%= user.posts.count %></p>
  </a>
</div>
<% end %>

app/views/users/show.html.erb
<h1>Here's the user info</h1>
<div>
  <img src="<%= @user.photo %>"/>
  <h2>User <strong><%= @user.name %></strong> ID from the URL: <%= params[:id] %></h2>
</div>
<div style="border: 1px solid #000; margin: 15px; display: flex; justify-content: space-between; align-items: center; padding: 1rem;">
  <div>
    <h3>Bio</h3>
    <p><%= @user.bio %></p>
  </div>
  <p>Number of posts: <%= @user.posts.count %></p>
</div>
<% if @recent_posts.empty? %>
  <div style="border: 1px solid #000; margin: 15px 15px 0 15px; padding: 1rem">
    <p>There are no posts yet</p>
  </div>
<% else %>
  <% @recent_posts.each do |post| %>
  <div style="border: 1px solid #000; margin: 15px; padding: 1rem;">
    <div style="display: flex; justify-content: space-between;">
      <div>
        <a href="<%= user_post_path(post.author, post)%>"><%= post.title %></a>
        <p><%= post.text %></p>
      </div>
      <div>
        <p>Comments: <%= post.comments_counter %></p>
        <p>Likes: <%= post.likes_counter %></p>
      </div>
    </div>
  </div>
  <% end %>
<% end %>
<a href="<%= user_posts_path(@user)%>"> See all posts </a>