config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  devise_for :users, controllers: {
    registrations: 'users/registrations',
    sessions: 'users/sessions',
    confirmations: 'users/confirmations'
  }
  # Defines the root path route ("/")
  root "users#index"

  resources :users, only: %i[index show] do
    resources :posts, only: %i[index show new create] do
      resources :comments, only: %i[index show new create edit update destroy]
      resources :likes, only: %i[index show create destroy]
    end
  end
end

app/models/post.rb
class Post < ActiveRecord::Base
  belongs_to :author, class_name: 'User'
  has_many :likes, class_name: 'Like', foreign_key: 'post_id'
  has_many :comments, class_name: 'Comment', foreign_key: 'post_id'

  def recent_comments
    comments.limit(5).order(created_at: :asc)
  end

  after_save :update_posts_counter

  private

  def update_posts_counter
    author.increment!(:posts_counter)
    author.save
  end

  validates :title, presence: true, length: { maximum: 250 }
  validates :comments_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
  validates :likes_counter, presence: true, numericality: { only_integer: true, greater_than_or_equal_to: 0 }
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  def index
    @user = User.find(params[:user_id])
    @posts = Post.includes(:author).where(author_id: params[:user_id]).paginate(page: params[:page], per_page: 5)
  end

  def new
    @user = current_user
    @post = Post.new
  end

  def create
    @post = Post.new(post_params)
    @post.author = current_user

    if @post.save
      puts 'Post saved correctly'
      flash[:success] = 'Post was successfully created.'
      redirect_to user_post_path(current_user, @post)
    else
      render :new
    end
  end

  def show
    @user = current_user
    @post = Post.find(params[:id])
    @comments = Comment.where(post_id: params[:id]).includes(:post)
  end

  private

  def post_params
    params.require(:post).permit(:title, :text)
  end
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/views/posts/_form.html.erb
<%= form_with model: [@user, @post], local: true do |f| %>
  <div>
    <%= f.label :title %>
    <%= f.text_field :title %>
  </div>
  <div>
    <%= f.label :text %>
    <%= f.text_area :text %>
  </div>
  <div>
    <%= f.submit "Create post" %>
  </div>
<% end %>

app/views/posts/index.html.erb
<div style="display: flex; margin: 15px; padding: 1rem; gap: 1rem">
  <img src="<%= @user.photo %>" />
  <div
    style="
      border: 1px solid #000;
      display: flex;
      justify-content: space-between;
      align-items: center;
      width: 100%;
      padding: 1rem;
    "
  >
    <h1>
      User <strong><%= @user.name %></strong> ID from the URL: <%= @user.id %>
    </h1>
    <p>Number of posts: <%= @user.posts.count %></p>
  </div>
</div>
<% if @posts.empty? %>
  <div style="border: 1px solid #000; margin: 15px 15px 0 15px; padding: 1rem">
    <p>There are no posts yet</p>
  </div>
<% else %>
  <% @posts.each_with_index do |post, index| %>
    <div style="border: 1px solid #000; margin: 15px 15px 0 15px; padding: 1rem">
      <div
        style="display: flex; justify-content: space-between"
      >
        <div style="display: flex; flex-direction: column">
          <a href="<%= user_post_path(post.author, post)%>" class="my-link" style="display: inline-block">
            Post #<%= index + 1 %> by <%= post.author.name %>
          </a>
          <p><%= post.title %></p>
          <p><%= post.text %></p>
        </div>
        <div>
          <p>Comments: <%= post.comments_counter %></p>
          <p>Likes: <%= post.likes_counter %></p>
        </div>
      </div>
    </div>
    <div style="border: 1px solid #000; padding: 1rem; margin: 0 15px 15px 15px">
      <% if post.recent_comments.empty? %>
      <p>There are no comments</p>
      <% else %> <% post.recent_comments.each do |comment|%>
      <p>Username: <%= comment.user.name %></p>
      <p><%= comment.text %></p>
      <% end%> <% end %>
    </div>
  <% end %>
<% end %>
<div>
  <a href="<%= new_user_post_path(current_user) %>">Create a new post</a>
</div>
<div class="pagination">
  <%= will_paginate @posts%>
</div>

app/views/posts/new.html.erb
<h1>Create a new Post</h1>
<%= render "form" %>

app/views/posts/show.html.erb
<h1>Details of a given Post</h1>
<div style="border: 1px solid #000; margin: 1rem; padding: 8px 1rem;">
  <div
    style="
      display: flex;
      justify-content: space-between;
      align-items: center;
    "
  >
    <h2>Post by username: <%= @post.author.name %> - <%= @post.title %></h2>
    <div style="display: flex; gap: 1rem">
      <p>Comments: <%= @post.comments_counter %></p>
      <p id="likes-counter">Likes: <%= @post.likes_counter %></p>
    </div>
  </div>
  <p>
    <%= @post.text %>
  </p>
  <div style="border: 1px solid #000; display: flex; flex-direction: column; gap: 1rem;">
    <% if @comments.empty? %>
      <p> There are no comments </p>
    <% else %>
      <% @comments.each do |comment| %>
        <div>
          <p>Username: <%= comment.user.name %></p>
          <p><%= comment.text %></p>
          <% if current_user == comment.user || current_user.role == 'admin' %>
            <%= render partial: 'comments/delete_form', locals: { comment: comment } %>
          <% end %>
        </div>
      <% end %>
    <% end %>
    <div id="post-<%= @post.id %>-like-buttons">
      <%= form_with url: user_post_likes_path(@user, @post), model: Like do |form| %>
        <%= form.hidden_field  :post_id, value: @post.id %>
        <div class='like-button'>
          <%= form.submit "Like post" %>
        </div>
      <% end %>
    </div>
    <div>
      <a href="<%= new_user_post_comment_path(@current_user, @post) %>">Create a new comment</a>
    </div>
  </div>
</div>